# https://github.com/pages-themes/minimal
theme: jekyll-theme-minimal
title: PursuedPyBear
description: Unbearably Fun Game Development
logo: /assets/bearlogo-270.png
show_downloads: true
# https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-mentions
